name: native_chat_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  animations: ^2.0.7
  dio: ^5.1.2
  flutter:
    sdk: flutter
  go_router: ^7.0.0
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  socket_io_client: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
